project: cpp-slib-cmake
description: >
  A template project using CMake which generates a static core library
  for Bocan Online C++ Projects.
language: C++
environment: CMake, Make
requires:
  - Git
  - CMake
  - Make
  - Clang
startup:
  - nvim . --(open editor at project root)
other:
  - ./scripts/build-debug.sh    --(build the debug configuration)
  - ./scripts/build-release.sh  --(build the release configuration)
  - ./scripts/run-debug.sh      --(run the application with debug config)
  - ./scripts/run-release.sh    --(run the application with release config)
  - ./scripts/build-clean.sh          --(remove build-debug/ and build-release/) 

