session_name: cpp
windows:
  - window_name: editor-project
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/cpp
      - nvim
  - window_name: shell
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/cpp

